### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by hiyyg** [thomasbrandon/mish-cuda#10]
Built with pytorch 1.7, cuda 10.2, TITAN X, got this error.

**Comment by thomasbrandon** [comment]
When doing what? Just posting part of an error message with no context makes it quite hard to know what's going on. At least post the full error with trace and what caused it.

**Comment by hiyyg** [comment]
fixed by adding 5.2 to TORCH_CUDA_ARCH_LIST
